### ISSUE TITLE
Ideas for Functor

### ISSUE THREAD

**Issue by darinmorrison** [epsilonz/shoggoth.rs#10]
So after a bunch of failed attempts, I've come up with the following encoding for functors that doesn't require any coercions. There's some boilerplate needed to make this work, as expected. However, it should be trivial to automate with a macro or attribute (e.g., `#[derive(HKT)]`).

Question is, how reasonable is this encoding, given the current limitations? Is there some obvious loophole I've overlooked? I haven't tried defining `Monad` or anything else but I think it should be possible.

/cc @jroesch @jonsterling 

```rust
mod hkt {
    use ty;

    // helpers; I _think_ these keep us honest… might need additional constraints
    pub trait Arg { type O; }
    pub trait Tag { type O; }
    pub trait Ins<T> { type O: Arg<O = Self> + Tag<O = T>; }

    // "apply" the higher-kinded tag to a type
    pub type Ap<T, A: Ins<T>> = <A as Ins<T>>::O;

    // boilerplate for Option
    pub enum OptionT {}
    impl<A> Arg for Option<A> { type O = A; }
    impl<A> Tag for Option<A> { type O = OptionT; }
    impl<A> Ins<OptionT> for A { type O = Option<A>; }

    // boilerplate for Vec
    pub enum VecT {}
    impl<A> Arg for Vec<A> { type O = A; }
    impl<A> Tag for Vec<A> { type O = VecT; }
    impl<A> Ins<VecT> for A { type O = Vec<A>; }

    // functor definition
    pub trait Functor<T>: Arg + Tag<O = T> {
        type A: Ins<T>;
        fn fmap<B, F>(self, f: F) -> Ap<T, B> where F: Fn(Self::A) -> B;
    }

    // "unapply" a type, yielding the parameter
    pub type Un<T, TX: Functor<T>> = <TX as Functor<T>>::A;
}

// functor for Option
impl<A> hkt::Functor<hkt::OptionT> for Option<A> {
    type A = A;
    fn fmap<B, F>(self, f: F) -> Option<B> where F: Fn(A) -> B
    {
        self.map(f)
    }
}

// functor for Vec
impl<A> hkt::Functor<hkt::VecT> for Vec<A> {
    type A = A;
    fn fmap<B, F>(self, f: F) -> Vec<B> where F: Fn(A) -> B
    {
        self.into_iter().map(f).collect()
    }
}

#[test]
fn foo() {
    // works pretty well inline
    println!("{}", Some(true).fmap(|&: b| !b).unwrap());
    println!("{}", vec![true, false].fmap(|&: b| !b)[0]);
}

#[test]
fn bar() {
    // bit more work to use generically; let's use a reference for the hell of it
    fn aux<T, TA, B, Clo>(m: TA, f: &Clo) -> hkt::Ap<T, B> where
        TA: hkt::Functor<T>,
        B: hkt::Ins<T>,
        Clo: Fn(hkt::Un<T, TA>) -> B
    {
        m.fmap(|&: x| f(x))
    }
    let f = |&: b: bool| !b;
    aux(Some(true), &f);
    aux(vec![true, false], &f);
}
```

**Comment by jonsterling** [comment]
Wow... Fwiw, I didn't know you could do that `T<A=B>` thing in Rust.

**Comment by darinmorrison** [comment]
Yeah, it's been a part of `associated_types` although until very recently a lot of little things with it didn't work. But now it's getting to be usable as part of the final push for 1.0.

**Comment by darinmorrison** [comment]
@jonsterling so I remember you had some reasonable objections to the initial `Functor` encoding for swiftz and I was wondering if you thought this approach was enough of an improvement to pursue. I don't quite understand what they're currently doing now but it doesn't seem quite like this afaict.

It's still an ugly hack of course, but then so is the rest of the library…

**Comment by jonsterling** [comment]
Well, the original Swift encoding was not adequate/sound—but I am afraid I do not know Rust well enough to be able to know whether this one is similarly problematic...

**Comment by darinmorrison** [comment]
I think that is still the case because in their version there are no constraints relating the type `A`, the return type of `fmap`, and the type of `Self`.

There is actually one problem with this version:

```rust
pub trait Functor<T>: Arg + Tag<O = T> {
        type A: Ins<T>;
        fn fmap<B, F>(self, f: F) -> Ap<T, B> where F: Fn(Self::A) -> B;
    }
```

The type `A` isn't as constrained as it should be. I think this would fix it:

```rust
pub trait Functor<T>: Arg<O = Self::A> + Tag<O = T>
```

But that doesn't work currently. However, this version does:

```rust
pub trait Functor<T>: hkt::Arg + hkt::Tag<O = T> {
    type X: hkt::Ins<T> + ty::Eq<<Self as hkt::Arg>::O>;
    #[inline]
    fn fmap<B, F>(self, f: F) -> hkt::Ap<T, B> where F: Fn(Self::X) -> B;
}
```

**Comment by darinmorrison** [comment]
Going to close this out. I think the final version (with `Eq` on `X`) is about as good as it's going to get without further additions to the language. As long as `Arg`, `Tag`, and `Ins` are defined correctly, this seems to rule out bad `Functor` implementations afaict. Luckily we can prove default implementations of those for most of the builtin types and provide a macro for deriving new ones.

**Comment by jroesch** [comment]
I meant to comment on this yesterday, I think this is about as good as we are going to get for now. We should start compiling a wish list of features for associated types and where clauses. 

Have you tried a Self type constraint Darin? You are able to give equality constraints on Self type and should be able to transitively relate `Vec<A>` to `VecT` and `A`.

You should be able to constraint Self using "poor man's" type equality. I did something like this the other day:
```
trait TyEq<A> 
impl<A> TyEq<A> for A {}

trait Functor<T>: Arg + Tag<O=T> where <Self as Arg>::O: TyEq<Self::A> {}
```

**Comment by darinmorrison** [comment]
I think I wasn't able to get `Self::X` to work in the outer `where` clause. Might have to try again.

**Comment by darinmorrison** [comment]
I believe I've come up with a better way to do this by thinking about how to generalize to the n-ary case and even nested types. The idea is to do away with the concept of the the `hkt::` tags and instead do some type-level programming over the shape or arity of the type. This seems like a more natural concept because we can compose traversals over the latter.

So instead of having `trait Functor<T>: Arg + Tag<O = T>` we would have `Functor<Path>: Compatible<Path>` where the path is used to both _project_ the `A` parameter from `TX` on the one hand and _replace_ `A` with `B` in `TX` on the other hand. Perhaps sort of like a lens.

```rust
// Example

// Option<_>
impl<X> Functor<(Z,)> for Option<X> {
    fn fmap<B>(self, f: F) -> Set<Self, (Z,), B> where F: Fn(Get<Self, (Z,)>) -> B {
        …
    }
}

// (A, (B, _,),)
impl<A, B, X> Functor<(S<Z>, S<Z>,)> for (A, (B, X,),) {
    fn fmap<C>(self, f: F) -> Set<Self, (S<Z>, S<Z>,), C> where F: Fn(Get<Self, (S<Z>, S<Z>,)>) -> C {
        …
    }
}
```

Another nice thing about this approach is that we could use default arguments to avoid having to specify the path at all for the most common case: `trait Functor<Path = (Z,)>` would do the right thing for cases like `Option<_>` and `Vec<_>` automatically.

I think this would also let us avoid the need for the equality constraint. This functionality ought to be useful for fancier categorical stuff than just `Functor` too.

Thoughts? /cc @aturon

**Comment by darinmorrison** [comment]
I've started to implement the refined approach but there are a number of other things that need to be put in place before it's usable. At the moment I'm working on some compiler plugins/macros to generate the boilerplate.
