### ISSUE TITLE
Use snoc hlists for thunk

### ISSUE THREAD

**Issue by freebroccolo** [epsilonz/shoggoth.rs#18]
In order to simplify the implementation of `AppEval` we just append to the end of the `HList` for `Thunk`. This works but it would be more efficient to use snoc hlists and have two implementations of `Prefix`.

**Comment by darinmorrison** [comment]
A better way to do this might be to use a defunctionalized representation of difference lists for all of the thunk stuff. That would give us cheap `snoc` as well as `append`. The latter would be useful for the multicomposition stuff.

**Comment by freebroccolo** [comment]
We have difference lists now which should be suitable for this purpose.
