### ISSUE TITLE
Revisit the Lens implementation

### ISSUE THREAD

**Issue by freebroccolo** [epsilonz/shoggoth.rs#22]
Currently, we're using a `StoreLike` trait which can be implemented for zippers or other appropriate structures for various types. This doesn't _prevent_ an underlying representation using the more modern functor style but we don't do anything to take advantage of it either.

The current problems doing away with `StoreLike` are 1) combinators would need more type parameters (I think), and 2) we'd need more machinery for the functor ops like `Const` and `Identity`.

The additional complexity from (2) would also make the implementation slower and I don't even have a good idea for how the type-checker will hold up under heavy use of the current stuff.

As far as (1) is concerned, we'd need simulated first-class (kind) polymorphism to avoid it, as far as I can tell. Since we already do something a bit like bidirectional type checking, this might not even be that far fetched but it still sounds a little silly. There might be a halfway point by hacking something a weak form of polymorphism into the `Thunk` machinery. However, even if we could do that I don't know if it would be enough for this use case.

**Comment by darinmorrison** [comment]
One thing I realized is that in actual usage, Rust seems to nearly always be capable of inferring the correct parameters if `_` is given in a type. There are some limitations on where this can be used though. In any case, it would mean that a compiler plugin could provide syntax for omitting the type parameters, expanding them to underscores.
