### ISSUE TITLE
Provide some examples

### ISSUE THREAD

**Issue by freebroccolo** [epsilonz/shoggoth.rs#8]
Right now it's probably hard to understand how to use any of this stuff. We should provide some examples or at least point folks to the tests.

**Comment by bwo** [comment]
how much of this is usable without the type macros? I remembered this project after wondering if the kiselyov/shan "implicit configurations" paper (aka kmett's reflection package) could be implemented in rust, and it looks like there's a lot of machinery defined that doesn't directly require the type macros, but I don't know if that impression is well founded.

(I'm commenting on this issue on the grounds that this is plausibly related to "how to use any of this stuff".)

**Comment by freebroccolo** [comment]
@bwo

Currently, I'm not sure if any of it is really usable on beta or master given some recent bugs like [this one](https://github.com/rust-lang/rust/issues/23714). Apparently there are some workaround but I haven't tried them yet.

There's also a serious [performance issue](https://github.com/rust-lang/rust/issues/22204) which makes even some simple type-level programs take a very long time to compile. The zipper tests in the old source tree exhibit this behavior. There's also an example [here](https://gist.github.com/freebroccolo/81f99ecd9923bf0845b4) using a fancy simulated HKT encoding that has the same problem.

As for macros, I decided to just commit to type macros wholeheartedly for the project. The reason being that even though you can do almost all of this stuff without it, it's just too painful in practice for most people to want to deal with I think. You can see what it looked like before type macros in the source tree [here](https://github.com/epsilonz/shoggoth.rs/tree/15d1b7b94057bb75d887c355d42afe5e1da6f503).

After I switched to type macros, the main use case I was focusing on was type-level numerics like for [indexed containers](https://gist.github.com/freebroccolo/5f43b737cc1c28c96896). Then, before the most recent problems, I was re-implementing the type-level numerics to use a much more efficient representation of naturals, which I prototyped in Haskell [here](https://github.com/freebroccolo/hs-ackermann). Most of the non-numeric machinery from before the switch to type macros hasn't been re-implemented yet.

So I guess the answer is that, with the current state of the code and what I'm planning for the future, the type macros part is pretty essential. But the issues with Rust I linked prevent most of this (with or without macros) from being usable in practice anyway. I'm hoping those will be resolved but I don't know when…

The "implicit configurations" thing is doable in Rust though. I have implemented the examples from the paper but not here. There's some related stuff in the reflect module (also see [machine.rs](https://github.com/freebroccolo/machine.rs)) in the current source tree though. Since Rust doesn't have higher-rank polymorphism, you have to end up using boxed traits and something more like "finally tagless" to build the type-level value. IIRC, there's a point at which you also need to use a `transmute` to implement one of the cases.
